import React from 'react';

export const pagesData: Record<string, { title: string; subtitle: string; content: React.ReactNode }> = {
  "ambassador": {
    title: "Winbox Ambassador Program",
    subtitle: "Represent Malaysia's Leading Platform & Earn Infinite Rewards",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Welcome to the <strong>Winbox Ambassador Program</strong>, the most rewarding partnership initiative in the online entertainment industry. As a Winbox Ambassador, you represent a trusted, premium brand and unlock endless earning potential through our lucrative commission structures.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Why Become a Winbox Ambassador?</h3>
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>High Conversion Rates:</strong> Benefit from our established brand reputation and extensive marketing efforts.</li>
            <li><strong>Lifetime Commissions:</strong> Earn a percentage of the revenue generated by players you refer, for life.</li>
            <li><strong>Exclusive Support:</strong> Access dedicated account managers, marketing materials, and real-time tracking tools.</li>
            <li><strong>VIP Perks:</strong> Enjoy special bonuses, event invitations, and prioritized customer service.</li>
          </ul>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">How to Join</h3>
          <p>
            Becoming an ambassador is simple. Register an account, navigate to the partnership section in your dashboard, and generate your unique referral link. Start sharing it across your networks to build your own entertainment empire.
          </p>
        </div>
      </>
    )
  },
  "brand-ambassador": {
    title: "Winbox Brand Ambassador",
    subtitle: "Elevating the Entertainment Experience Together",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            The <strong>Winbox Brand Ambassador</strong> role is an exclusive partnership designed for influencers, public figures, and industry leaders who share our vision of providing the ultimate gaming and entertainment experience.
          </p>
          <p>
            Our brand ambassadors are the face of Winbox, embodying our core values of trust, excitement, and innovation. They collaborate with us on high-profile marketing campaigns, social media outreach, and exclusive events.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Benefits of the Role</h3>
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>Custom Sponsorship Packages:</strong> Tailored compensation models including fixed fees and performance bonuses.</li>
            <li><strong>Brand Synergy:</strong> Co-branded promotional campaigns to elevate both our platform and your personal brand.</li>
            <li><strong>Exclusive Access:</strong> VIP treatment at all Winbox-sponsored events and tournaments.</li>
          </ul>
          <p>
            If you have a strong following and want to represent a leading brand, contact our marketing team today to discuss collaboration opportunities.
          </p>
        </div>
      </>
    )
  },
  "agent": {
    title: "Winbox Agent Program",
    subtitle: "Build Your Own Business with Winbox",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Take control of your financial future by joining the <strong>Winbox Agent Program</strong>. As an agent, you step into a managerial role, recruiting and managing your own downline of players and sub-agents.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">The Agent Advantage</h3>
          <p>
            Unlike standard referrals, agents have access to an advanced backend management system. This allows you to track player activity, manage downline commissions, and optimize your marketing strategies with precision data.
          </p>
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>Multi-Tier Commissions:</strong> Earn from your direct players and from the network built by your sub-agents.</li>
            <li><strong>Comprehensive Dashboard:</strong> Monitor daily, weekly, and monthly performance metrics in real-time.</li>
            <li><strong>Automated Payouts:</strong> Enjoy hassle-free commission settlements directly to your preferred withdrawal method.</li>
            <li><strong>Marketing Support:</strong> Utilize our professional banners, landing pages, and promotional content.</li>
          </ul>
          <p>
            Whether you are an experienced affiliate marketer or looking to start a new venture, the Winbox Agent Program provides the tools you need to succeed.
          </p>
        </div>
      </>
    )
  },
  "referrer": {
    title: "Winbox Referrer Guide",
    subtitle: "Share and Earn with Every Friend",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            The <strong>Winbox Referrer</strong> system is the easiest way to start earning. Simply invite your friends to experience the excitement of Winbox, and get rewarded when they join and play.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">How It Works</h3>
          <ol className="list-decimal pl-6 space-y-3">
            <li><strong>Get Your Link:</strong> Log in to your Winbox account and find your unique referral QR code and link.</li>
            <li><strong>Share:</strong> Send the link to friends via WhatsApp, Telegram, WeChat, or social media.</li>
            <li><strong>Earn:</strong> Receive continuous rebate commissions based on the gameplay activity of your referred friends.</li>
          </ol>
          <p>
            There is no limit to how many friends you can refer. The more you share, the more passive income you can generate. Start building your referral network today!
          </p>
        </div>
      </>
    )
  },
  "register-tutorial": {
    title: "How to Register on Winbox",
    subtitle: "Step-by-Step Guide to Creating Your Account",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Joining Winbox is fast, secure, and entirely free. Follow this simple guide to set up your account and start enjoying our extensive range of games.
          </p>
          <div className="bg-sky-50 border border-sky-100 rounded-2xl p-6 mt-6">
            <h3 className="text-xl font-bold text-sky-900 mb-4">Registration Steps</h3>
            <ol className="list-decimal pl-5 space-y-4 text-sky-800">
              <li><strong>Visit the Registration Page:</strong> Click the "Register" button at the top right of the homepage.</li>
              <li><strong>Enter Your Details:</strong> Provide a unique Username and a secure Password.</li>
              <li><strong>Verify Your Phone Number:</strong> Enter your active mobile number to receive a verification code via SMS.</li>
              <li><strong>Input the Code:</strong> Enter the OTP (One-Time Password) to confirm your identity.</li>
              <li><strong>Complete Registration:</strong> Click submit. Your account is now active and ready to use!</li>
            </ol>
          </div>
          <p className="text-sm mt-4 text-gray-500">
            Note: Please ensure your phone number is correct, as it will be required for account recovery and withdrawals.
          </p>
        </div>
      </>
    )
  },
  "top-up-methods": {
    title: "Winbox Top Up Methods",
    subtitle: "Fast, Secure, and Convenient Deposits",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            We offer a variety of secure top-up methods to ensure your gaming experience is never interrupted. All transactions are protected by industry-leading encryption.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Available Methods</h3>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="border border-gray-200 rounded-xl p-5 shadow-sm">
              <h4 className="font-bold text-gray-900 text-lg mb-2">Online Banking</h4>
              <p className="text-sm">Instant transfers via FPX supporting all major Malaysian banks (Maybank, CIMB, Public Bank, etc.).</p>
            </div>
            <div className="border border-gray-200 rounded-xl p-5 shadow-sm">
              <h4 className="font-bold text-gray-900 text-lg mb-2">E-Wallets</h4>
              <p className="text-sm">Quick deposits using popular e-wallets like Touch 'n Go, Boost, and GrabPay.</p>
            </div>
            <div className="border border-gray-200 rounded-xl p-5 shadow-sm">
              <h4 className="font-bold text-gray-900 text-lg mb-2">Cryptocurrency (USDT)</h4>
              <p className="text-sm">Secure and private deposits using USDT (TRC20/ERC20) for rapid blockchain transfers.</p>
            </div>
            <div className="border border-gray-200 rounded-xl p-5 shadow-sm">
              <h4 className="font-bold text-gray-900 text-lg mb-2">ATM / Cash Deposit</h4>
              <p className="text-sm">Manual bank transfers are supported. Upload your receipt for verification.</p>
            </div>
          </div>
        </div>
      </>
    )
  },
  "withdraw-tutorial": {
    title: "How to Withdraw from Winbox",
    subtitle: "A Quick Guide to Cashing Out Your Winnings",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Cashing out your winnings on Winbox is a seamless process. We pride ourselves on fast withdrawal processing times, ensuring you get your funds quickly and securely.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Withdrawal Steps</h3>
          <ol className="list-decimal pl-6 space-y-3">
            <li><strong>Bind Your Bank Account:</strong> Before your first withdrawal, navigate to 'Account Settings' and link your personal bank account. The name must match your registered real name.</li>
            <li><strong>Go to the Withdrawal Section:</strong> Click on your wallet balance and select 'Withdraw'.</li>
            <li><strong>Enter Amount:</strong> Input the amount you wish to cash out. Ensure you meet the minimum withdrawal requirement.</li>
            <li><strong>Submit Request:</strong> Confirm the transaction. Most withdrawals are processed within 5 to 15 minutes.</li>
          </ol>
          <p className="mt-4 font-bold text-red-600">
            Important: Ensure all turnover requirements from bonuses are met before requesting a withdrawal.
          </p>
        </div>
      </>
    )
  },
  "ekor-tutorial": {
    title: "Ekor (Lottery) Tutorial",
    subtitle: "How to Play and Win the Lottery",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            The <strong>Ekor Lottery</strong> on Winbox offers access to all major 4D providers in Malaysia and Singapore, including Magnum, Da Ma Cai, Sports Toto, Singapore Pools, and more.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">How to Place a 4D Bet</h3>
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>Select the Provider:</strong> Open the Lottery section and choose your preferred 4D operator.</li>
            <li><strong>Choose Your Numbers:</strong> Enter your lucky 4-digit numbers.</li>
            <li><strong>Select Bet Type:</strong> Choose between Big (Besar) or Small (Kecil). 'Big' covers all prize categories, while 'Small' offers higher payouts for the top 3 prizes.</li>
            <li><strong>Enter Bet Amount:</strong> Input your wager and confirm the ticket.</li>
          </ul>
          <p>
            Results are updated live on draw days (Wednesdays, Saturdays, Sundays, and Special Draws). Winnings are credited automatically to your Winbox wallet.
          </p>
        </div>
      </>
    )
  },
  "horse-racing-tutorial": {
    title: "Horse Racing Tutorial",
    subtitle: "Master the Track and Place Winning Bets",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Experience the thrill of live horse racing from top tracks around the world, right here on Winbox. Our platform provides live streams, real-time odds, and comprehensive race cards.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Common Bet Types</h3>
          <div className="bg-gray-50 p-6 rounded-xl space-y-4">
            <div>
              <strong className="text-gray-900">Win:</strong> You bet on a specific horse to finish first.
            </div>
            <div>
              <strong className="text-gray-900">Place:</strong> You bet on a horse to finish in the top positions (usually 1st, 2nd, or 3rd, depending on the field size).
            </div>
            <div>
              <strong className="text-gray-900">Quinella:</strong> Pick two horses to finish 1st and 2nd in any order.
            </div>
            <div>
              <strong className="text-gray-900">Tierce:</strong> Predict the exact 1st, 2nd, and 3rd place finishers in the correct order.
            </div>
          </div>
          <p className="mt-4">
            To get started, navigate to the Sports/Racing section, select today's race meeting, analyze the form guide, and place your bet before the jump.
          </p>
        </div>
      </>
    )
  },
  "real-name-authentication": {
    title: "Real Name Authentication",
    subtitle: "Securing Your Account and Funds",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            At Winbox, security is our top priority. <strong>Real Name Authentication</strong> is a mandatory step to ensure the safety of your funds and prevent fraudulent activities.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Why is it Required?</h3>
          <p>
            Binding your real name ensures that withdrawals can only be made to a bank account that belongs to you. This protects your wallet balance even if your account is compromised.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">How to Bind Your Name</h3>
          <ol className="list-decimal pl-6 space-y-3">
            <li>Go to <strong>Me</strong> &gt; <strong>Account Security</strong>.</li>
            <li>Select <strong>Real Name Authentication</strong>.</li>
            <li>Enter your full name exactly as it appears on your ID and Bank Account.</li>
            <li>Confirm and save.</li>
          </ol>
          <p className="text-red-500 font-bold mt-4">
            Note: Once bound, your real name cannot be changed easily. Please double-check for typos before submitting.
          </p>
        </div>
      </>
    )
  },
  "usdt-deposit": {
    title: "USDT Deposit Tutorial",
    subtitle: "Fund Your Account with Cryptocurrency",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Winbox supports <strong>USDT (Tether)</strong> deposits, offering a fast, borderless, and highly secure way to fund your gaming wallet.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Step-by-Step Guide</h3>
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>Access the Deposit Page:</strong> Go to your wallet and select 'Deposit', then choose 'USDT'.</li>
            <li><strong>Select Network:</strong> Choose your preferred blockchain network (TRC20 is recommended for lower fees and faster speeds).</li>
            <li><strong>Copy Address:</strong> A unique wallet address and QR code will be generated. Copy this address.</li>
            <li><strong>Transfer Funds:</strong> Open your crypto exchange or personal wallet, paste the address, and send your desired USDT amount.</li>
            <li><strong>Confirmation:</strong> Once the blockchain network confirms the transaction, your Winbox balance will be updated automatically based on the live exchange rate.</li>
          </ul>
        </div>
      </>
    )
  },
  "usdt-withdrawal": {
    title: "USDT Withdrawal Tutorial",
    subtitle: "Cash Out Seamlessly via Crypto",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Withdrawing your winnings via USDT provides privacy and rapid settlement times. Follow these steps to process a crypto withdrawal.
          </p>
          <div className="bg-sky-50 p-6 rounded-2xl mt-6">
            <h3 className="text-xl font-bold text-sky-900 mb-4">Withdrawal Process</h3>
            <ol className="list-decimal pl-5 space-y-4 text-sky-800">
              <li>Navigate to the <strong>Withdrawal</strong> page and select <strong>USDT</strong>.</li>
              <li>Bind your receiving USDT wallet address (Ensure you select the correct network, e.g., TRC20 or ERC20).</li>
              <li>Enter the withdrawal amount. The system will display the estimated USDT you will receive based on current rates.</li>
              <li>Submit the request and enter your security PIN.</li>
              <li>The funds will be transferred to your crypto wallet shortly after processing.</li>
            </ol>
          </div>
          <p className="mt-4 text-sm text-gray-500">
            Warning: Sending funds to an incorrect address or mismatched network will result in permanent loss of funds. Always double-check your wallet address.
          </p>
        </div>
      </>
    )
  },
  "privacy": {
    title: "Privacy Policy",
    subtitle: "How We Protect Your Data",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Your privacy is critically important to us. This Privacy Policy outlines how Winbox collects, uses, and safeguards your personal information when you use our platform.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Information Collection</h3>
          <p>
            We collect information necessary to provide a secure gaming environment, including your phone number, real name (for banking verification), and transaction history.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Data Protection</h3>
          <p>
            All data transmitted between your device and our servers is encrypted using 128-bit SSL technology. We employ advanced firewall protections to prevent unauthorized access to our databases.
          </p>
          <h3 className="text-2xl font-black text-gray-900 mt-8 mb-4">Information Sharing</h3>
          <p>
            Winbox strictly does not sell, rent, or trade your personal information to third parties. Data is only shared with payment providers strictly for the purpose of processing your deposits and withdrawals.
          </p>
        </div>
      </>
    )
  },
  "promo": {
    title: "Winbox Promotions & Bonuses",
    subtitle: "Maximize Your Winnings with Our Exclusive Offers",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Welcome to the Winbox Promotions page. We believe in rewarding our players generously. Take advantage of these incredible bonuses to boost your bankroll.
          </p>
          <div className="grid md:grid-cols-2 gap-6 mt-8">
            <div className="border border-sky-100 bg-sky-50 rounded-2xl p-6">
              <h4 className="font-black text-sky-900 text-xl mb-2">100% Welcome Bonus</h4>
              <p className="text-sm mb-4">Double your first deposit instantly up to RM500. Exclusively for new members.</p>
              <ul className="text-xs space-y-1 text-sky-800 list-disc pl-4">
                <li>Minimum deposit: RM50</li>
                <li>Turnover requirement: 15x</li>
              </ul>
            </div>
            
            <div className="border border-green-100 bg-green-50 rounded-2xl p-6">
              <h4 className="font-black text-green-900 text-xl mb-2">Daily Deposit Bonus</h4>
              <p className="text-sm mb-4">Get a 10% bonus on your first deposit every single day.</p>
              <ul className="text-xs space-y-1 text-green-800 list-disc pl-4">
                <li>Maximum bonus: RM100</li>
                <li>Turnover requirement: 5x</li>
              </ul>
            </div>

            <div className="border border-orange-100 bg-orange-50 rounded-2xl p-6">
              <h4 className="font-black text-orange-900 text-xl mb-2">Rescue Bonus</h4>
              <p className="text-sm mb-4">Down on your luck? Claim up to 5% weekly cashback on your net losses.</p>
              <ul className="text-xs space-y-1 text-orange-800 list-disc pl-4">
                <li>Calculated weekly</li>
                <li>No turnover required</li>
              </ul>
            </div>

            <div className="border border-purple-100 bg-purple-50 rounded-2xl p-6">
              <h4 className="font-black text-purple-900 text-xl mb-2">Birthday Bonus</h4>
              <p className="text-sm mb-4">Celebrate your special day with a free RM88 bonus on us!</p>
              <ul className="text-xs space-y-1 text-purple-800 list-disc pl-4">
                <li>Must verify ID</li>
                <li>Valid during birth month</li>
              </ul>
            </div>
          </div>
        </div>
      </>
    )
  },
  "contact": {
    title: "Contact Us",
    subtitle: "We Are Here to Help 24/7",
    content: (
      <>
        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p>
            Have a question, need assistance with a transaction, or want to provide feedback? The Winbox customer support team is available 24 hours a day, 7 days a week.
          </p>
          
          <div className="grid md:grid-cols-3 gap-6 mt-8">
            <div className="flex flex-col items-center text-center p-6 bg-white border border-gray-100 rounded-2xl shadow-lg shadow-gray-100">
              <div className="w-12 h-12 bg-sky-100 text-sky-600 rounded-full flex items-center justify-center mb-4 text-xl font-black">LC</div>
              <h4 className="font-bold text-gray-900 mb-2">Live Chat</h4>
              <p className="text-sm text-gray-500">Fastest response. Access the chat directly from the bottom right corner of the website.</p>
            </div>
            
            <div className="flex flex-col items-center text-center p-6 bg-white border border-gray-100 rounded-2xl shadow-lg shadow-gray-100">
              <div className="w-12 h-12 bg-green-100 text-green-600 rounded-full flex items-center justify-center mb-4 text-xl font-black">WA</div>
              <h4 className="font-bold text-gray-900 mb-2">WhatsApp</h4>
              <p className="text-sm text-gray-500">Reach out to our official WhatsApp support channel for secure messaging.</p>
            </div>
            
            <div className="flex flex-col items-center text-center p-6 bg-white border border-gray-100 rounded-2xl shadow-lg shadow-gray-100">
              <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mb-4 text-xl font-black">TG</div>
              <h4 className="font-bold text-gray-900 mb-2">Telegram</h4>
              <p className="text-sm text-gray-500">Join our Telegram channel for support and the latest promotional updates.</p>
            </div>
          </div>
        </div>
      </>
    )
  }
};
